name: Android CI

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Application version"
        required: true
        default: "1.0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
        cache: gradle
    - name: Decode Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: "android_keystore.jks"
        fileDir: "/home/runner/work/bookmark_attempt_6/bookmark_attempt_6/app/keystore/"
        encodedString: ${{ secrets.KEYSTORE }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK
      run: |
        ./gradlew :app:assembleRelease -x test
        mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/app-release.apk

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        alias: Knight
        keyStorePassword: Ashim2056
        keyPassword: Knight2056
      env:
      # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "30.0.2"

    - name: Current date time
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1.2.0
      with:
        format: "YYYY_MM_DD HH_mm_ss_SSS"

    - name: Move Signed App
      run: |
         mv app/build/outputs/apk/app-release-signed.apk app/Bookmarks.apk


    - name: Upload APK
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Bookmarks
        path: app/Bookmarks.apk

    - name: Download APK from build
      uses: actions/download-artifact@v1
      with:
        name: Bookmarks

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_REPOSITORY: Kotlin-Apps-Death-Knight-552/Simple-Bookmarks

      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release - ${{ steps.date.outputs.time }}
        draft: true
        prerelease: false
        files: Simple-Bookmarks/Bookmarks.apk
